

global:
  freq: 300
  buffer_size: 2048
  velo_limits: [50.0, 70.0, 75.0, 75.0, 350.0, 350.0, 400.0]
  contact_threshold: 3.0
  C_q: [1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0, 1000.0]
  C_v: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
  C_y: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]
  C_f: [30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0]


leader:
  ip: "127.0.0.1"
  robot: "172.22.2.3" #vincent
  port: 49185
  p_vals: [750.0, 600.0, 600.0, 600.0, 70.0, 100.0, 50.0]
  d_vals: [30.0, 50.0, 50.0, 50.0, 12.0, 20.0, 10.0]


follower:
  ip: "127.0.0.1"
  robot: "172.22.2.4" #bob
  port: 49186
  p_vals: [750.0, 600.0, 600.0, 600.0, 70.0, 100.0, 50.0]
  d_vals: [30.0, 50.0, 50.0, 50.0, 12.0, 20.0, 10.0]